version: '3.4'

services:
  fpm:
    volumes:
      - './:/srv/pim'
      - '../export:/export'
  mysql:
    volumes:
      - '../db:/var/lib/mysql/'
      - '../dump:/dump/'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: 'always'
    environment:
      PMA_HOST: 'mysql'
    ports:
      - "9191:80"
    networks:
      - 'pim'
